version: '3.9'

services:
  cs-gy-6613-project:
    build:
      context: "."
      dockerfile: ./docker/Dockerfile.dev.gpu 
    image: cs-gy-6613-project
    platform: linux/arm64  
    shm_size: '8gb'
    user: vscode
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - PLATFORM=macos
    networks:
      - cs-gy-6613-project-net
networks:
  cs-gy-6613-project-net:
    driver: bridge

volumes:
  minio_data:
  rye-cache: