services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  cs-gy-6613-project:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer
    # folder. Note that the path of the Dockerfile and context is relative to the *primary*
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev.gpu
      cache_from:
        - cs-gy-6613-project:latest
    image: cs-gy-6613-project:latest
    user: vscode
    # ports:
    #   - 9000:9000 # Minio's HTTP port
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspaces/cs-gy-6613-project:cached
      - rye-cache:/home/vscode/.rye/cache  # Persist the Rye cache

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    

